name: Docker

on:
  push: 
    branches:
    - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::966924987919:role/DistributedProgrammingEx
    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build docker image
      env:
        ECR_RESISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: distributed-programming-ex
        DOKCER_BUILDKIT: 1
      run: |
        docker pull $ECR_RESISTRY/$ECR_REPOSITORY:latest || true
        docker build -t $ECR_RESISTRY/$ECR_REPOSITORY:latest --cache-from=$ECR_RESISTRY/$ECR_REPOSITORY --build-arg BUILDKIT_INLINE_CACHE=1 UID=1001 GID=115 .
        docker push $ECR_RESISTRY/$ECR_REPOSITORY:latest