name: Docker

on:
  push: 
    branches:
    - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::966924987919:role/DistributedProgrammingEx
    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build docker image
      env:
        ECR_RESISTORY: ${{ steps.ecr-login.outputs.resistory }}
        ECR_REPOSITORY: distributed-programming-ex
      run: |
        docker build -t $ECR_RESISTORY/$ECR_REPOSITORY:latest
        docker push -t $ECR_RESITORY/$ECR_REPOSITORY:latest