name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::966924987919:role/DistributedProgrammingEx
    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
    - name: Pull docker image
      env:
        ECR_RESISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: distributed-programming-ex
      run: docker pull $ECR_RESISTRY/$ECR_REPOSITORY:latest
    - name: Build mochi-intro
      env:
        ECR_RESISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: distributed-programming-ex
      run: >-
        docker run
        --mount type=bind,source=$(pwd),target=/work
        -t $ECR_RESISTRY/$ECR_REPOSITORY:latest /work/mochi-intro/ci.sh